### ISSUE TITLE
Comments on invokable operations functionality

### ISSUE THREAD

**Issue by tmarble** [DEX-Company/starfish-java#74]
This issue is really used simply as a vehicle to comment on the recent additions regarding invokable operations.

This looks good and is idiomatic Java (using **java.util.concurrent**). Handing asynchrony is really important and we will likely need to revisit this when we get to a web services (RESTful) version of the API (where we cannot, for example, assume in-process java.util.concurrent waiting/blocking features).

Detailed comments follow:

https://github.com/DEX-Company/starfish-java/commit/dc2b924f2710a3873f2ffe75174441c77179a381
You mention not having public construtors, and here there is
one in MemoryJob.. should it be protected?

In terms of style it would probably be best, at function creation time,
to add Javadoc comments right away. Note that the Javadoc tools
will complain if @params or @returns do not have a description.
FFI:
https://www.oracle.com/technetwork/articles/java/index-137868.html

https://github.com/DEX-Company/starfish-java/commit/71fc0939e1edfdbbd9f36b45aff330aef814c322
w.r.t. AOperation(String meta) ...

So, for example, in this constructor we understand 'meta' to
be the string representation of metadata. And, I believe, the
'canonical' representation for metadata will be a JSONObject
(and we'll have handy utilities to round trip JSONObject <-> String).
In terms of API design itself.. should we standardize on
one constructor like this that takes metadata as a String?
Should we have one constructor taking JSONObject? Or two
constructors (that leverage the utility conversion methods)?

I see this decision has an impact on the idea (expressed in this
later commit) to cache the conversion of metadata... 
Why wouldn't it be better to simply pass in an immutable JSONObject
vs. a metadata string?
  https://github.com/DEX-Company/starfish-java/commit/850239dbe27220f0d3653ba1af52b2858571a874

https://github.com/DEX-Company/starfish-java/commit/546c9e43fdfb4f1a592ab1b8cd6db69c9aa8c0b7

So great to have the test added along with the new functionality
so we can see the intended use pattern!

**Comment by mikera** [comment]
Hi Tom, thanks for the detailed comments. Feel free to add commits / PRs on documentation where you find things missing. I've addressed most of your comments in a new PR for your review.

Regarding the JSONObject, this is actually mutable since we are using json-simple at the moment rather than the javax JSONObject (which has the nice property of being immutable, but the not-so nice disadvantage of not converting elements to convenient Java types). We could consider a switch but would need some careful consideration re: developer ergonomics.
