### ISSUE TITLE
invoke() signature confusion

### ISSUE THREAD

**Issue by tmarble** [DEX-Company/starfish-java#77]
It seems like the interface **InvokableAgent** really, instead,
wants to be called **Invokable**
  AND it should also have the the getParamSpec() method
  (as currently in **Operation**)
because any invoke() interface *must* be able to describe the required parameters.

* http://shrimp.octet.services/starfish/starfish-java/latest/apidocs/sg/dex/starfish/InvokableAgent.html
* http://shrimp.octet.services/starfish/starfish-java/latest/apidocs/sg/dex/starfish/Operation.html#getParamSpec--

QUESTION: here the *order* of params in invoke is significant (i.e.
  presumably semantics are given to positional order) but the Map
  does NOT supply keys in order!

However, the [reference to DEP 6](https://github.com/DEX-Company/DEPs/tree/master/6#examples) suggests that the signature
for invoke() is incorrect  and should, instead, be something more like
  public Job invoke(Map<String,Asset>);
 where the name of each asset parameter matches that with the metadata in the
  JSONObject as returned by getParamSpec()

In this way...
1. Operation becomes Asset + Invokable (and isOperation())

2. public class InvokeAgent extends AAgent implements Invokable 

Thoughts?

**Comment by mikera** [comment]
Why not `InvokableAgent`? Do you see situations where the Invokable thing is not an agent (remote or otherwise)?

An operation might not be Invokable in its own right (e.g. a script can't be invoked unless you have an agent that knows how to execute it).

Param ordering is a separate issue, I agree we should have a version with named parameters as per DEP6 but I also like the idea of supporting positional arguments, which can be done with paramspecs that define certain parameters as being in a specified position, e.g.

`{  "param1": {
   "type": "asset",
   "description": "The one and only parameter to this operation",
   "position": "0"
}
}`

**Comment by tmarble** [comment]
The primary rationale for **Invokable** is that it seems like the signature of Operation.invoke may very well want to be using the same interface: https://github.com/DEX-Company/starfish-java/blob/develop/src/main/java/sg/dex/starfish/Operation.java#L35

I'm completely fine to keep it **InvokableAgent** as long as the intention of the Operation.invoke is not the
same (or would not benefit from sharing the interface).

The positional arguments (esp. varargs) form is succinct. If we support that should getParamSpec() return parameter specs in some sort of (stable) order (e.g. **ArrayList**)

**Comment by mikera** [comment]
Hmmmm I think in general the signatures are a bit different so they need a different interface. You have:

`agent.invoke(operation,params)`
vs.
`operation.invoke(params)`

The second only works if either:
a) The operation can be completed without an agent or
b) The operation maintains a reference to an agent that it can use (e.g. an in-memory operation)

For positional arguments, I favour having an optional "position" field for each argument in the paramspec. This makes it clear that named arguments are the standard, but positional arguments can be used for convenience if the operation supports it in the paramspec. @kkarkera see current implementation.

**Comment by tmarble** [comment]
Ah, ok, thanks for pointing it out.. much cleadrly on both points.
